//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PivotReportClasses {
    
    private PivotReportClassesPivotReportClass[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PivotReportClass", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public PivotReportClassesPivotReportClass[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class PivotReportClassesPivotReportClass {
    
    private string entite_concerne_f;
    
    private string fichier_pivot_f;
    
    private string fichier_pivot_renommee_f;
    
    private string id_de_suivi_f;
    
    private string statut_f;
    
    private string uploader_f;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string entite_concerne {
        get {
            return this.entite_concerne_f;
        }
        set {
            this.entite_concerne_f = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fichier_pivot {
        get {
            return this.fichier_pivot_f;
        }
        set {
            this.fichier_pivot_f = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fichier_pivot_renommee {
        get {
            return this.fichier_pivot_renommee_f;
        }
        set {
            this.fichier_pivot_renommee_f = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string id_de_suivi {
        get {
            return this.id_de_suivi_f;
        }
        set {
            this.id_de_suivi_f = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string statut {
        get {
            return this.statut_f;
        }
        set {
            this.statut_f = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string uploader {
        get {
            return this.uploader_f;
        }
        set {
            this.uploader_f = value;
        }
    }
}
